apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity
spec:
  selector:
    matchLabels:
      app: capstone
  replicas: 2
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: michalkrasucki/capstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

kind: Service
metadata:
  name: udacity
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
